# Generated by Django 6.0.3 on 2026-04-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_image_profile_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_path',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default/dealer.png', max_length=255, null=True, upload_to='uploads/profile_images/', verbose_name='Аватар'),
        ),
    ]
