# Generated by Django 6.0.3 on 2026-04-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_image_path_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default/dealer.png', null=True, upload_to='uploads/profile/', verbose_name='Аватар'),
        ),
    ]
