# Generated by Django 6.0.3 on 2026-04-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, default='default/shell.jpg', null=True, upload_to='uploads/rooms/', verbose_name='Изображение'),
        ),
    ]
